version: "3"

services:
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - redis:/data

  app:
    image: dmitryrck/ruby
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
      - REDIS_URL=redis://redis:6379
    working_dir: /app
    command: puma -p 3000
    ports:
      - 3000:3000
    depends_on:
      - "redis"

volumes:
  bundle_path:
  redis:
