name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: docker-compose pull
      - run: docker-compose run --rm -e RAILS_ENV=test app bundle install --jobs=4 --retry=3
      - run: docker-compose run --rm app bundle exec rspec
